modLoader="javafml"
loaderVersion="[31,)"
license="GNU General Public License v3.0"

[[mods]]
modId="krayscandles"
namespace="krayscandles"
version="1.0.4"
displayName="Kray's Magic Candles"
authors="Captain Kray, Calemi, Kryto627"
credits="Thanks to all the members of Team Monumental for inspiring me to make this mod."
description='''
    This mod adds a variety of candles, light sources, and the candle making process into minecraft.
    '''

[[dependencies.cspirit]]
modId="forge"
mandatory=true
versionRange="[31,)"
ordering="NONE"
side="BOTH"